services:
  hefesto:
    container_name: hefesto
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    # labels:
    #   - 'traefik.enable=true'
    #   - 'traefik.http.routers.hefesto.rule=Host(`hefesto.like`)'
    #   - 'traefik.http.routers.hefesto.entrypoints=web'
    #   - 'traefik.http.services.hefesto.loadbalancer.server.port=80'
    # networks:
    #   - traefik-net
    ports:
      - '2008:80'

# networks:
#   traefik-net:
#     external: true
