<script setup lang="ts">
import JSON5 from 'json5';
import { withDefaultOnError } from '../../utils/defaults';
import type { UseValidationRule } from '@/composable/validation';

import { jsonToGo } from '@/utils/json-to-go';

function convertJsonToGo(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) return '';

  let parsed: unknown;
  try {
    parsed = JSON5.parse(trimmed);
  } catch {
    return '';
  }

  const { go, error } = jsonToGo(JSON.stringify(parsed), {
    typeName: 'AutoGenerated',
    flatten: true,
  });

  return error ? '' : go.trim();
}

function transformer(value: string): string {
  return value.trim() === '' ? '' : withDefaultOnError(() => convertJsonToGo(value), '');
}

const rules: UseValidationRule<string>[] = [
  {
    validator: (v: string) =>
      v.trim() === '' ||
      (() => {
        JSON5.parse(v);
        return true;
      })(),
    message: 'Provided JSON is not valid.',
  },
];
</script>

<template>
  <format-transformer
    input-label="Your JSON"
    input-placeholder="Paste your JSON here..."
    output-label="Go structure from your JSON"
    output-language="go"
    :input-validation-rules="rules"
    :transformer="transformer"
  />
</template>
