import { expect, test } from '@playwright/test';

test.describe('Tool - JSON to Go', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/json-to-go');
  });

  test('Converte JSON em struct Go', async ({ page }) => {
    await page.getByTestId('input').fill(
      `{
        "name": "Alice",
        "age": 30,
        "admin": true
      }`,
    );

    const output = await page.getByTestId('area-content').innerText();

    expect(output).toContain('type AutoGenerated struct');
    expect(output).toContain('Name string');
    expect(output).toContain('Age int');
    expect(output).toContain('Admin bool');
  });
});
